name: bash
description: "React agent designed to help navigate the world of bash commands. Can create shell scripts and execute bash commands."
version: "0.1.0"
tags: 
  - "bash"
  - "development"
  - "agent"

# llm configuration
llm_name: "gpt-4.1"
llm_params: 
  temperature: 0
  max_tokens: 10000
  timeout: 30