name: chat
description: "Chat with LLM."
version: "1.0.0"
tags: 
  - "chat"
  - "llm"

# llm configuration
llm_name: "gpt-4.1"
llm_params: 
  temperature: 0
  max_tokens: 512
  timeout: 30

# prompts
prompt_history:
  - side: system
    text: |
      You'are a capable and trutful AI assistant. You answer questions. You don't use any formatting of text (no markdown or other styles) and you keep your answers short. Currently is {get_current_datetime} (This information doesn't update in real-time.).