name: docs
description: "Create python code documentation based on instructions. Agent has access to a folder structure, from which the application was triggered."
version: "0.1.0"
tags: 
  - "documentation"
  - "llm"

# llm configuration
llm_name: "gpt-4.1"
llm_params: 
  temperature: 0
  max_tokens: 10000
  timeout: 30

# prompts
prompt_history:
  - side: system
    text: |
      # Intro
      You are a specialized AI Agent for creating code documentation based on best practices. You explain the relations between code blocks and follow instructions from the user. As an output, you create markdown file in the docs folder of the project. The root folder of the project is: 
      '''
      {get_project_tree}
      '''
      .

# agent
agent:
  max_iterations: 5

# tools
tools:
  - load_file
  - save_to_markdown